---

- hosts: ansible-vm
  environment:
    JAVA_HOME: /usr/java/default
  roles:
    - role: ansible-weblogic
      weblogic_jar_path: '/files/fmw_12.1.3.0.0_infrastructure.jar'
      weblogic_quick_installation: false
      weblogic_installation_type: 'Fusion Middleware Infrastructure'
      weblogic_domain_name: 'oac_domain'
      middleware_dir: '/u01/app/oracle/product/middleware1213'
      nodemanager_listen_port: 5557
      adminserver_listen_port: 7002
      managed_server_listen_port: 7004
    
    - role: ansible-oac
      oac_jar_path: '/files/oer_generic.jar'
      oracle_db_address: '127.0.0.1'
      oracle_db_sid: 'orcl'
      oracle_db_password: 'password'
      oac_admin_server_listen_address: '127.0.0.1'
      oac_managed_server_listen_address: '127.0.0.1'
