---

- hosts: ansible-vm
  environment:
    JAVA_HOME: /usr/java/default
  roles:
    - role: ansible-oag
      oag_prefix: "{{ oracle_base_dir }}/product/oag"
      oag_username: 'admin'
      oag_password: 'password'
      oag_hostname: '127.0.0.1'
      oag_port: '8090'
      oag_external_port: '8080'
      oag_local_mgmt_port: '8085'
